#!/bin/bash

# New Robot Install

apt-get update
apt-get install software-properties-common -y
add-apt-repository ppa:ubuntu-toolchain-r/test -y
apt-get update
apt-get dist-upgrade -y
apt-get install vim wireless-tools wpasupplicant -y

wpa_passphrase epsilon-x 9181918191 > /etc/wpa_supplicant/wpa_supplicant.conf

cat << EOF > /etc/network/interfaces
# This file describes the network interfaces available on your system
# and how to activate them. For more information, see interfaces(5).

# Loopback
auto lo
iface lo inet loopback

# Ethernet
auto eth0
iface eth0 inet dhcp

# WiFi
auto wlan0
iface wlan0 inet dhcp
pre-up wpa_supplicant -B -Dwext -i wlan0 -c /etc/wpa_supplicant/wpa_supplicant.conf
post-up iwconfig wlan0 power off
post-down killall -q wpa_supplicant
EOF

ifup wlan0

cat << EOF > /etc/udev/rules.d/100-darwin.rules
# Set permissions for ttyUSB0 (CM730) and video* (webcam) devices
KERNEL=="ttyUSB*", MODE="0666"
KERNEL=="video*", MODE="0666"

# Symlink the CM730 device to /dev/CM730
KERNEL=="ttyUSB*", ATTRS{idVendor}=="0403", ATTRS{idProduct}=="6001", MODE="0666", SYMLINK+="CM730"

# Symlink the Logitech CM920 webcam to /dev/CAM
KERNEL=="video*", ATTRS{idVendor}=="046d", ATTRS{idProduct}=="082d", MODE="0666", SYMLINK+="CAM"

# Symlink the Creative Labs LIVE! CAM Chat HD webcam to /dev/CAM
KERNEL=="video*", ATTRS{idVendor}=="041e", ATTRS{idProduct}=="4097", MODE="0666", SYMLINK+="CAM"
EOF

cat << EOF > /etc/rc.local
#!/bin/sh -e
#
# rc.local
#
# This script is executed at the end of each multiuser runlevel.
# Make sure that the script will "exit 0" on success or any other
# value on error.
#
# In order to enable or disable this script just change the execution
# bits.
#
# By default this script does nothing.

# Set volume to 100%
amixer sset Master 100%

# Start PS3 bluetooth daemon
su -l -c "screen -S ps3 bash -c 'sixad --start'" darwin

# Disable CPU throttling
update-rc.d ondemand disable

exit 0
EOF

# Install robocup.conf to /etc/init (when using upstart) to allow robocup to autostart
if [ -d "/usr/share/upstart" ]; then
    cat << EOF > /etc/init/robocup.conf
    description "RoboCup auto-start unit"

    start on (started networking)
    stop on runlevel [!2345]

    respawn

    script
      export HOME="/home/darwin/"
      export LD_LIBRARY_PATH="/home/darwin/toolchain"
      cd /home/darwin
      ./robocup > $(date +%s)".log"
    end script
    EOF

# Install robocup.service to /etc/systemd/system (when using systemd) to allow robocup to autostart
else
    cat << EOF > /etc/systemd/system/robocup.service
    [Unit]
    Description="RoboCup auto-start unit"
    Wants=network.target
    After=network.target
    RequiresMountsFor=/home/darwin

    [Service]
    Type=simple
    Restart=always
    WorkingDirectory=/home/darwin
    User=darwin
    Environment=HOME="/home/darwin/" LD_LIBRARY_PATH="/home/darwin/toolchain"
    PassEnvironment=HOME LD_LIBRARY_PATH
    ExecStart=/home/darwin/robocup

    [Install]
    WantedBy=multi-user.target
    EOF

    # Enable autostarting of the service
    systemctl enable robocup.service
fi

# Remove network delay by commenting out the delays
sed -ri 's/(sleep (:?20|40|59))/#\1/' /etc/init/failsafe.conf

# Added boot fail fix
sed -i '/GRUB_CMDLINE_LINUX=""/a GRUB_RECORDFAIL_TIMEOUT=0' /etc/default/grub
update-grub

# Remove password requirement to use sudo
sed -ri 's/(%sudo.*)(ALL)/\1NOPASSWD:\2/' /etc/sudoers

# Add PS3 controller tools
apt-add-repository ppa:falk-t-j/qtsixa -y
apt-get update
apt-get install sixad -y
