#!/bin/bash

# New Robot Install

apt-get update
apt-get dist-upgrade -y
apt-get install vim wireless-tools wpasupplicant -y

wpa_passphrase epsilon-xtreme 9181918191 > /etc/wpa_supplicant/wpa_supplicant.conf

cat << EOF > /etc/network/interfaces
# This file describes the network interfaces available on your system
# and how to activate them. For more information, see interfaces(5).

# Loopback
auto lo
iface lo inet loopback

# Ethernet
auto eth0
iface eth0 inet dhcp

# WiFi
auto wlan0
iface wlan0 inet dhcp
pre-up wpa_supplicant -B -Dwext -i wlan0 -c /etc/wpa_supplicant/wpa_supplicant.conf
post-up iwconfig wlan0 power off
post-down killall -q wpa_supplicant
EOF

ifup wlan0

cat << EOF > /etc/udev/rules.d/100-darwin.rules
KERNEL=="ttyUSB0", MODE="0666"
KERNEL=="video0", MODE="0666"
EOF

cat << EOF > /etc/rc.local
#!/bin/sh -e
#
# rc.local
#
# This script is executed at the end of each multiuser runlevel.
# Make sure that the script will "exit 0" on success or any other
# value on error.
#
# In order to enable or disable this script just change the execution
# bits.
#
# By default this script does nothing.

# Set volume to 100%
amixer sset Master 100%

# Start PS3 bluetooth daemon
su -l -c "screen -S ps3 bash -c 'sixad --start'" darwin

# Disable CPU throttling
update-rc.d ondemand disable

exit 0
EOF

# Remove network delay by commenting out the delays
sed -ri 's/(sleep (:?20|40|59))/#\1/' /etc/init/failsafe.conf

# Added boot fail fix
sed -i '/GRUB_CMDLINE_LINUX=""/a GRUB_RECORDFAIL_TIMEOUT=0' /etc/default/grub
update-grub

# Remove password requirement to use sudo
sed -ri 's/(%sudo.*)(ALL)/\1NOPASSWD:\2/' /etc/sudoers

# Add PS3 controller tools
apt-get install software-properties-common -y
apt-add-repository ppa:falk-t-j/qtsixa -y
apt-get update
apt-get install sixad -y